### ISSUE TITLE
no documentation (my fork attempt to address this problem at least a little bit)

### ISSUE THREAD

**Issue by ForestJohnson** [letorbi/fontie#1]
Check out https://github.com/ForestJohnson/fontie#how-to-use 

Feel free to expand this or merge it at your leisure.  I am currently waiting for fontie/fontforge to attempt to optimize https://www.fontspace.com/blackpine-font-f56304  its been running for about 10 minutes... no wonder it timed out when I uploaded it to https://fontie.pixelsvsbytes.com/webfont-generator !! 

Cheers and much love for this awesome project. I hope it works for me.

**Comment by letorbi** [comment]
Hej Forest,

thanks for writing some documentation! This is great, because writing some installation guidelines was on my todo-list for years, but I was never able to start with it due to other tasks with higher priority. I really appreciate your work.

Could you create a pull request, so that I can merge your changes into my repo? Well, actually two PRs might be even better: One for the documentation and one for the changes you've made to get Fontie running on your system.

Regarding the text I would prefer, if it is written from a more "general perspektive" (less "I") - sorry, I don't know how to describe it better. It would also be nice if "How to use" could be named "Installation" and "Sending a request using cURL" could be a level-two headline.

Anyway, if you don't have any time for changing the text, I could do it as well, but I would be great, if you could create the pull requests, so that the one who did all the work - you - is also mentioned in the commits ;)

Thanks again,
Torben

**Comment by ForestJohnson** [comment]
> Regarding the text I would prefer, if it is written from a more "general perspektive" (less "I") - sorry, I don't know how to describe it better.

Yes,  I was not trying to create general documentation for you, it was more like I was simply creating a journal entry documenting my progress. I didn't have the energy to attempt to create a universal doc that would work for everyone.

TBH I kinda gave up halfway through as well because unfortunately the output I got at the end of the 10minutes long process was garbled. I guess all those errors weren't just warnings after all:

![image](https://user-images.githubusercontent.com/7119703/121910328-5f6d0980-ccf4-11eb-8ee3-f1d2e1287419.png)

and the resulting file size (700k -> 220k) wasn't small enough for my use case . (the fonts I did end up using were compressed down to about 15k apiece) I think if I wanted to use this blackpine font I would have to rasterize it into a sprite map texture (like how Unity game engine handles fonts) and build my own javascript font rendering engine similar to [Cufón](https://github.com/sorccu/cufon). But I don't have the time for that and I don't like how it makes it so you can't select the text to copy and paste.

![image](https://user-images.githubusercontent.com/7119703/121910474-7dd30500-ccf4-11eb-9301-4fd4038c88de.png)

**Comment by ForestJohnson** [comment]
I will at least go over it once and edit for formality and what not .

**Comment by letorbi** [comment]
> Yes, I was not trying to create general documentation for you, [...] I didn't have the energy to attempt to create a universal doc that would work for everyone.

> I will at least go over it once and edit for formality and what not .

No worries, if you don't have the time and energy I'll do the final edits. Your work is a good foundation anyway :)

> I kinda gave up halfway through as well because unfortunately the output I got at the end of the 10minutes long process was garbled. I guess all those errors weren't just warnings after all

Well, could be - too bad it didn't work out for you. Hopefully I'll find some time to try Fontie with Blackpine. I'll write you my findings then.

> [...] the resulting file size (700k -> 220k) wasn't small enough for my use case .

Have you tried to subsetting? If you know what chars you need, you can only include these in the resulting font-file and leave out the rest. This should drastically reduce the file-size.

Thanks for the PRs. I'll check them out this evening.

**Comment by ForestJohnson** [comment]
Yes that result included subsetting to the ascii range.  I believe its because the font is made from a high res image of dry marker caligraphy being converted to vectors with tons of fine detail. I was hoping that fontie / fontforge could reduce the detail  gracefully enough for use but it looks like maybe not.

I  should say its not that fontie wasn't useful to me at all, it definitely was (those 10kb fonts that I am using are only 10kb because of fontie!!), it just wasn't able to reduce the  font vectors level of detail as much as I had hoped.   Again, cheers for creating this great project :smile:  :beers:
